### ISSUE TITLE
Additional sources

### ISSUE THREAD

**Issue by dkoltg** [rnckp/awesome-ogd-switzerland#2]
Thank you for the list with all the links to impartant data sources. You could add the Canton Thurgau as well in the categories geodata (see https://map.geo.tg.ch/apps/mf-geoadmin3/?lang=de&topic=ech) and further data sources (https://statistik.tg.ch) as those websites correspond from my point of way to the already added ones.

**Comment by rnckp** [comment]
Thanks for you suggestions! 👍

- I have added statistik.tg.ch and the thematic atlases. 
- I also quickly looked into the geo spatial offering (map.geo.tg.ch). However, I couldn't find any option to export geo data (which is my criteria to include an offering). Have I missed something here or is it indeed just an interactive map with no data export options?

**Comment by dkoltg** [comment]
Thanks for adding the sources :). Regarding map.geo.tg.ch you are right that within the GIS-Viewer you can't export data directly. However, there are links provided to all the datasets where you can get the data (data.tg.ch or shop.geo.tg.ch).

**Comment by rnckp** [comment]
Thanks for the clarification. I have added the geo data links. 😊
