### ISSUE TITLE
Linked Data

### ISSUE THREAD

**Issue by JurekMueller** [rnckp/awesome-ogd-switzerland#3]
That is a great and very useful list! Thank you for compiling this!
You might want to also include the OGD Linked Data endpoints and events such as:
https://lindas.admin.ch/ecosystem/
https://fedlex.data.admin.ch/de-CH/home/intro
https://www.bfh.ch/de/themen/linked-data-meetup/

And projects like:
https://lobbywatch.ch/de/seite/datenexport

**Comment by rnckp** [comment]
Thanks for your positive feedback and your suggestions!

I have added all the links to the list. Merci! 👍😊

**Comment by rnckp** [comment]
Thanks for your positive feedback and your suggestions!

I have added all the links to the list. 

Merci! 👍😊
