### ISSUE TITLE
Additional geodata Uri

### ISSUE THREAD

**Issue by lisagur** [rnckp/awesome-ogd-switzerland#5]
Thanks for the nice list!
In my opinion, you could also add the Canton Uri as well by the geodata:

Overviewsite: https://www.ur.ch/geoinformationen
Cantonal geoportal, with the possibility to download data: https://geo.ur.ch/?

**Comment by rnckp** [comment]
Thanks for the positive feedback and the suggestion!

I have added the links. 👍
