### ISSUE TITLE
swisspost dead

### ISSUE THREAD

**Issue by claudep** [rnckp/awesome-ogd-switzerland#8]
swisspost.opendatasoft.com is dead (confirmed by a post.ch email that they stopped the service). The successor should be https://developer.apis.post.ch/ui/apis, but I'm struggling since many weeks to obtain from the post.ch support to have an access (the address service should be free, but needs approval). :sob:

**Comment by rnckp** [comment]
Thanks for the heads up, Claude. I appreciate that. I have removed the obsolete link. 

Thanks also for the link to Swissposts developer portal. Sound unfortunate if they make access to their data services so difficult. 😟
