### ISSUE TITLE
New Open Data repo from MeteoSwiss

### ISSUE THREAD

**Issue by mchaamsler** [rnckp/awesome-ogd-switzerland#9]
Dear Patrick

MeteoSwiss' repo about its Open Data preparation towards 1 April 2025 changed. The continuously updated, valid Open Data documentation is [here](https://github.com/MeteoSwiss/opendata/blob/main/README.md). The old repo's content is outdated, and will soon be taken offline

Many thanks for switching to the new repo's URL.

Best, Andreas

**Comment by rnckp** [comment]
Dear Andreas

Thanks for the heads up! I have updated the link. 👍

Have a great evening!

Cheers, 

Patrick
